### ISSUE TITLE
I ask you to review the problem as soon as possible, please

### ISSUE THREAD

**Issue by nez11111** [iambotop/instant-marks-by-iambotop#1]
The program has stopped working since yesterday, giving me a notice that there is a problem

**Comment by iambotop** [comment]
You're college might have turned off "web services API" which is how the
program gets the grade, to check it out your self goto their website ex: "
school.com/moodle/login/token.php?username=yourusername&password=yourpassword&service=moodle_mobile_app
"

**Comment by nez11111** [comment]
> web services API

Well, is there another way to get the marks?
Or will they turn on Web Service API during the next exam? 
thank you

**Comment by iambotop** [comment]
I don't know, that's something you have to sort out with your college's IT
department but my guess is they intentionally turned it off to prevent
students from getting their marks early.
